image: alpine:latest
pages:
  stage: deploy
  script:
  - mkdir .public
  - mv .well-known well-known
  - cp -r * .public
  - mv .public public
  - mv .public/well-known public/.well-known
  artifacts:
    paths:
    - public
  only:
  - master
